const team = [
    {
      name: "Kalyan Veeramachaneni",
      slug: "kalyan",
      location: "Boston, MA",
      title: 'Co-Founder',
      text: 'Previously at Feature Labs (acq. Alteryx), PatternEx (acq. Corelight)',
      mit: 'MIT',
      image: '/team/kalyan.png',
      linkedin: "https://www.linkedin.com/in/kalyan-veeramachaneni-9861b821/",
      twitterUrl: "https://twitter.com/kveeramac",
      facebookUrl: "",
      website: "",
    },
    {
      name: "Carles Sala",
      slug: "carles",
      location: "Boston, MA",
      title: 'VP of Architecture & Engineering, Co-Founder',
      text: '',
      mit: 'Previously at MIT',
      image: '/team/carles.png',
      linkedin: "https://www.linkedin.com/in/carlessalacladellas/",
      twitterUrl: "https://twitter.com/csalacat",
      facebookUrl: "",
      website: "",
    },
    {
      name: "Neha Patki",
      slug: "neha",
      location: "Boston, MA",
      title: "Director of Product, Co-Founder",
      text: "Previously at Youtube, Google",
      mit: 'MIT 2016',
      image: "/team/neha.png",
      linkedin: "https://www.linkedin.com/in/nehapatki/",
      twitterUrl: "https://twitter.com/n4atki",
      facebookUrl: "",
      website: "",
    },
    {
      name: "Saman Amarsinghe",
      slug: "saman",
      location: "Boston, MA",
      title: 'Co-Founder',
      text: 'Previously at Determina (acq. VMWare)',
      mit: 'MIT',
      image: '/images/team/Saman_Amarasinghe_transparent.png',
      linkedin: "https://www.linkedin.com/in/saman/ ",
      twitterUrl: "https://twitter.com/samanprabhath",
      facebookUrl: "",
      website: "",
    },
    {
      name: "Andrew Montanez",
      slug: "andrew",
      location: "Boston, MA",
      title: 'Senior Software Engineer',
      text: 'Previously at Rev',
      mit: 'MIT 2018',
      image: '/team/Andrew.png',
      linkedin: "https://www.linkedin.com/in/andrew-montanez-593247b2/",
      twitterUrl: "",
      facebookUrl: "",
      website: "",
    },
    {
      name: "Plamen Valentinov",
      slug: "plamen",
      location: "Boston, MA",
      title: 'Developer Advocate & Software Engineer',
      text: '',
      mit: 'Previously at MIT',
      image: '/images/team/Plamen_Valentinov_transparent.png',
      linkedin: "https://www.linkedin.com/in/plamen-valentinov-kolev/",
      twitterUrl: "https://twitter.com/pvkdeveloper",
      facebookUrl: "",
      website: "",
    },
    {
      name: "Katharine Xiao",
      slug: "katharine",
      location: "Boston, MA",
      title: 'Senior Software Engineer',
      text: 'Previously at Facebook, Rubrik',
      mit: 'MIT 2017',
      image: '/images/team/Katharine_Xiao_transparent.png',
      linkedin: "https://www.linkedin.com/in/katharine-x-5238365a/",
      twitterUrl: "",
      facebookUrl: "",
      website: "",
    },
    {
      name: "Felipe Hofmann",
      slug: "felipe",
      location: "Boston, MA",
      title: 'Software Engineer',
      text: '',
      mit: 'MIT 2020',
      image: '/images/team/Felipe_Hofmann_transparent.png',
      linkedin: "https://www.linkedin.com/in/felipe-hofmann-347231a8/",
      twitterUrl: "",
      facebookUrl: "",
      website: "",
    },
  ]


  export default team;